name: Build and Release .deb

on:
  push:
    tags:
      - "v*"

jobs:
  build-deb:
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v') && github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set VERSION from tag
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev dos2unix rlpr lpr pdftk qrencode imagemagick perl

      - name: Build .deb
        run: fakeroot make

      - name: Create GitHub Release with changelog
        uses: softprops/action-gh-release@v1
        with:
          files: magic-utils_*.deb
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
